[build-system]
requires = [ "setuptools>=61.0.0", "wheel", "setuptools_scm" ]

[project]
name = "omuse-framework"
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "src/omuse/version.py"
relative_to = "__file__",
root = "../.."

[tool.setuptools.dynamic]
version = {attr = "omuse-framework.VERSION"}
