[build-system]
requires = [ "setuptools>=65.0.0", "wheel", "setuptools_scm", "numpy" ]

[project]
name = "omuse-framework"
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "src/omuse/version.py"
root = "../.."
