#! /bin/sh

set -e
format=ext
if [ yes = yes ]; then
  exec >test_cksum_$format.log 2>&1
  ./cksum_write -f $format
  ./cksum_read example.$format
  \rm example.cksum example.$format
  \rm test_cksum_$format.log
else
  # skip tests for unsupported formats
  exit 77
fi
