* Generated by CDO operator gradsdes
*
DSET  ^pl_data.grb
DTYPE  GRIB
INDEX  ^pl_data.gmp
XDEF 12 LINEAR -165.000000 30.000000
YDEF 6 LINEAR -75.000000 30.000000
ZDEF 4 LEVELS 900 90 9 0.9 
TDEF 5 LINEAR 12:00Z02jan1978 1dy
TITLE  pl_data.grb  12x6 grid
UNDEF  -9e+33
VARS  3
t                  4  130,100  temperature  [K]
lsp                0  152,1  log surface pressure
geosp              0  129,1  surface geopotential (orography)  [m^2/s^2]
ENDVARS
