--- cdo-1.7.0rc5/src/Makefile	2017-02-08 13:18:05.883553560 +0100
+++ src_original/src/Makefile	2016-12-14 21:29:52.949609436 +0100
@@ -774,6 +774,22 @@
 	@rm -f cdo$(EXEEXT)
 	$(AM_V_CCLD)$(cdo_LINK) $(cdo_OBJECTS) $(cdo_LDADD) $(LIBS)
 
+#############################################################
+#inserts by Ben van Werkhoven
+#############################################################
+MAIN_OBJ = cdo-cdo.$(OBJEXT)
+AMUSE_OBJS = $(filter-out $(MAIN_OBJ),$(cdo_OBJECTS))
+
+libcdo-cdolib.a:
+	echo "Building CDO library for AMUSE"
+	ar ruv libcdo-cdolib.a $(AMUSE_OBJS)
+	ranlib libcdo-cdolib.a
+
+
+#############################################################
+#end of inserts by Ben
+#############################################################
+
 cdotest$(EXEEXT): $(cdotest_OBJECTS) $(cdotest_DEPENDENCIES) $(EXTRA_cdotest_DEPENDENCIES) 
 	@rm -f cdotest$(EXEEXT)
 	$(AM_V_CCLD)$(cdotest_LINK) $(cdotest_OBJECTS) $(cdotest_LDADD) $(LIBS)
