--- cdo-1.7.0rc5/src/Makefile	2015-09-01 11:39:59.910086219 +0200
+++ src/src/Makefile	2015-09-01 11:21:51.463805003 +0200
@@ -369,19 +369,19 @@
 ETAGS = etags
 CTAGS = ctags
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
-ACLOCAL = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/cdo/cdo-1.7.0rc5/config/missing aclocal-1.14
+ACLOCAL = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/remapper/src/config/missing aclocal-1.14
 AMTAR = $${TAR-tar}
 AM_CPPFLAGS = 
 AM_DEFAULT_VERBOSITY = 1
 AR = ar
 AS = as
-AUTOCONF = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/cdo/cdo-1.7.0rc5/config/missing autoconf
-AUTOHEADER = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/cdo/cdo-1.7.0rc5/config/missing autoheader
-AUTOMAKE = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/cdo/cdo-1.7.0rc5/config/missing automake-1.14
+AUTOCONF = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/remapper/src/config/missing autoconf
+AUTOHEADER = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/remapper/src/config/missing autoheader
+AUTOMAKE = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/remapper/src/config/missing automake-1.14
 AWK = gawk
 CC = gcc -std=gnu99
 CCDEPMODE = depmode=gcc3
-CFLAGS = -g -O2 -Wall -g -fopenmp 
+CFLAGS = -g -O2 -fopenmp 
 CLDFLAGS = 
 CLIBS = 
 CMOR_LIBS = 
@@ -392,7 +392,7 @@
 CXX = g++
 CXXCPP = g++ -E
 CXXDEPMODE = depmode=gcc3
-CXXFLAGS = -g -O2 -g -O2 -Wall -g
+CXXFLAGS = -g -O2
 CYGPATH_W = echo
 DEFS = -DHAVE_CONFIG_H
 DEPDIR = .deps
@@ -416,7 +416,7 @@
 ENABLE_NETCDF = yes
 ENABLE_SERVICE = yes
 EXEEXT = 
-FCFLAGS = -g -O2
+FCFLAGS = 
 FGREP = /bin/grep -F
 GREP = /bin/grep
 GRIB_API_INCLUDE = 
@@ -443,7 +443,7 @@
 MAGICS_LIBS = 
 MAGICS_ROOT = 
 MAINT = #
-MAKEINFO = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/cdo/cdo-1.7.0rc5/config/missing makeinfo
+MAKEINFO = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/remapper/src/config/missing makeinfo
 MANIFEST_TOOL = :
 MKDIR_P = /bin/mkdir -p
 NC_CONFIG = nc-config
@@ -487,13 +487,13 @@
 XML2_LIBS = 
 ZLIB_INCLUDE = 
 ZLIB_LIBS =  -lz
-abs_builddir = /home/ben/amuse/amuse-svn/src/omuse/community/cdo/cdo-1.7.0rc5/src
-abs_srcdir = /home/ben/amuse/amuse-svn/src/omuse/community/cdo/cdo-1.7.0rc5/src
-abs_top_builddir = /home/ben/amuse/amuse-svn/src/omuse/community/cdo/cdo-1.7.0rc5
-abs_top_srcdir = /home/ben/amuse/amuse-svn/src/omuse/community/cdo/cdo-1.7.0rc5
+abs_builddir = /home/ben/amuse/amuse-svn/src/omuse/community/remapper/src/src
+abs_srcdir = /home/ben/amuse/amuse-svn/src/omuse/community/remapper/src/src
+abs_top_builddir = /home/ben/amuse/amuse-svn/src/omuse/community/remapper/src
+abs_top_srcdir = /home/ben/amuse/amuse-svn/src/omuse/community/remapper/src
 ac_ct_AR = ar
 ac_ct_CC = gcc
-ac_ct_CXX = 
+ac_ct_CXX = g++
 ac_ct_DUMPBIN = 
 am__include = include
 am__leading_dot = .
@@ -521,7 +521,7 @@
 htmldir = ${docdir}
 includedir = ${prefix}/include
 infodir = ${datarootdir}/info
-install_sh = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/cdo/cdo-1.7.0rc5/config/install-sh
+install_sh = ${SHELL} /home/ben/amuse/amuse-svn/src/omuse/community/remapper/src/config/install-sh
 libdir = ${exec_prefix}/lib
 libexecdir = ${exec_prefix}/libexec
 localedir = ${datarootdir}/locale
@@ -774,6 +774,23 @@
 	@rm -f cdo$(EXEEXT)
 	$(AM_V_CCLD)$(cdo_LINK) $(cdo_OBJECTS) $(cdo_LDADD) $(LIBS)
 
+
+#############################################################
+#inserts by Ben van Werkhoven
+#############################################################
+MAIN_OBJ = cdo-cdo.$(OBJEXT)
+AMUSE_OBJS = $(filter-out $(MAIN_OBJ),$(cdo_OBJECTS))
+
+libcdo-cdolib.a:
+	echo "Building CDO library for AMUSE"
+	ar ruv libcdo-cdolib.a $(AMUSE_OBJS)
+	ranlib libcdo-cdolib.a
+
+
+#############################################################
+#end of inserts by Ben
+#############################################################
+
 cdotest$(EXEEXT): $(cdotest_OBJECTS) $(cdotest_DEPENDENCIES) $(EXTRA_cdotest_DEPENDENCIES) 
 	@rm -f cdotest$(EXEEXT)
 	$(AM_V_CCLD)$(cdotest_LINK) $(cdotest_OBJECTS) $(cdotest_LDADD) $(LIBS)
@@ -4558,7 +4575,7 @@
 	maintainer-clean maintainer-clean-generic mostlyclean \
 	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
 	pdf pdf-am ps ps-am tags tags-am uninstall uninstall-am \
-	uninstall-binPROGRAMS
+	uninstall-binPROGRAMS libcdo-amuse.a
 
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
